Attributes {
    HDF_GLOBAL {
    }
    CoreMetadata {
        OrbitNumber {
            Int32 Value -9999;
            String Data_Location PGE;
            String Mandatory FALSE;
        }
        RangeBeginningDate {
            String Value 1998/09/09;
            String Data_Location PGE;
            String Mandatory FALSE;
        }
        TMIRolloverCoef {
            String Value "(-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9)";
            String Data_Location PGE;
            String Mandatory FALSE;
        }
        hack {
            Int32 value 2, 3, 5, 7, 11;
            String name "primes";
        }
    }
    percipitate_dim_0 {
        String name "scan";
    }
    percipitate_dim_1 {
        String name "longitude";
    }
    percipitate_dim_2 {
        String name "latitude";
    }
    relError_dim_0 {
        String name "scan";
    }
    relError_dim_1 {
        String name "longitude";
    }
    relError_dim_2 {
        String name "latitude";
    }
}
